{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "chatserver.serviceAccountName" . }}
  labels:
{{ include "chatserver.labels" . | indent 4 }}
{{- end -}}
